# Generated by Django 5.2.9 on 2025-12-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_techstack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='technologies/')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='portfolio.technology'),
        ),
        migrations.DeleteModel(
            name='TechStack',
        ),
    ]
