# Generated by Django 5.2.9 on 2025-12-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_technology_profile_technologies_delete_techstack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='icon',
        ),
    ]
