# Generated by Django 5.2.9 on 2025-12-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_project_tech_stack_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma separated, e.g. Django, React', max_length=200, null=True),
        ),
    ]
