# Generated by Django 5.2.9 on 2025-12-05 08:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resume'),
        ),
    ]
